const MOVIES = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/wRxLAw4l17LqiFcPLkobriPTZAw.jpg',
      id: 697843,
      title: 'Extraction 2',
      original_language: 'en',
      original_title: 'Extraction 2',
      overview:
        "Tasked with extracting a family who is at the mercy of a Georgian gangster, Tyler Rake infiltrates one of the world's deadliest prisons in order to save them. But when the extraction gets hot, and the gangster dies in the heat of battle, his equally ruthless brother tracks down Rake and his team to Sydney, in order to get revenge.",
      poster_path: '/7gKI9hpEMcZUQpNgKrkDzJpbnNS.jpg',
      media_type: 'movie',
      genre_ids: [28, 53],
      popularity: 1180.988,
      release_date: '2023-06-12',
      video: false,
      vote_average: 7.869,
      vote_count: 522,
    },
    {
      adult: false,
      backdrop_path: '/7e9MVGg8efOhoA2R9XhZcGWTC5Z.jpg',
      id: 298618,
      title: 'The Flash',
      original_language: 'en',
      original_title: 'The Flash',
      overview:
        "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
      poster_path: '/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg',
      media_type: 'movie',
      genre_ids: [878, 28, 12],
      popularity: 1732.233,
      release_date: '2023-06-14',
      video: false,
      vote_average: 6.864,
      vote_count: 409,
    },
    {
      adult: false,
      backdrop_path: '/q7XOgkp0NfjqVRYxzU0eGg7wSrm.jpg',
      id: 42009,
      name: 'Black Mirror',
      original_language: 'en',
      original_name: 'Black Mirror',
      overview:
        "A contemporary British re-working of The Twilight Zone with stories that tap into the collective unease about our modern world. \n\nOver the last ten years, technology has transformed almost every aspect of our lives before we've had time to stop and question it. In every home; on every desk; in every palm - a plasma screen; a monitor; a smartphone - a black mirror of our 21st Century existence.",
      poster_path: '/5UaYsGZOFhjFDwQh6GuLjjA1WlF.jpg',
      media_type: 'tv',
      genre_ids: [10765, 18, 9648],
      popularity: 969.485,
      first_air_date: '2011-12-04',
      vote_average: 8.312,
      vote_count: 4114,
      origin_country: ['GB'],
    },
    {
      adult: false,
      backdrop_path: '/6l1SV3CWkbbe0DcAK1lyOG8aZ4K.jpg',
      id: 385687,
      title: 'Fast X',
      original_language: 'en',
      original_title: 'Fast X',
      overview:
        "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
      poster_path: '/fiVW06jE7z9YnO4trhaMEdclSiC.jpg',
      media_type: 'movie',
      genre_ids: [28, 80, 53],
      popularity: 8893.249,
      release_date: '2023-05-17',
      video: false,
      vote_average: 7.3,
      vote_count: 1802,
    },
    {
      adult: false,
      backdrop_path: '/nTvM4mhqNlHIvUkI1gVnW6XP7GG.jpg',
      id: 85937,
      name: 'Demon Slayer: Kimetsu no Yaiba',
      original_language: 'ja',
      original_name: '鬼滅の刃',
      overview:
        'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.',
      poster_path: '/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg',
      media_type: 'tv',
      genre_ids: [16, 10759, 10765],
      popularity: 394.559,
      first_air_date: '2019-04-06',
      vote_average: 8.694,
      vote_count: 5315,
      origin_country: ['JP'],
    },
    {
      adult: false,
      backdrop_path: '/vnPTLSBk95XKdahOaMkTlAck5Rc.jpg',
      id: 882569,
      title: "Guy Ritchie's The Covenant",
      original_language: 'en',
      original_title: "Guy Ritchie's The Covenant",
      overview:
        'During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.',
      poster_path: '/kVG8zFFYrpyYLoHChuEeOGAd6Ru.jpg',
      media_type: 'movie',
      genre_ids: [10752, 28, 53],
      popularity: 990.636,
      release_date: '2023-04-19',
      video: false,
      vote_average: 7.629,
      vote_count: 588,
    },
    {
      adult: false,
      backdrop_path: '/2I5eBh98Q4aPq8WdQrHdTC8ARhY.jpg',
      id: 569094,
      title: 'Spider-Man: Across the Spider-Verse',
      original_language: 'en',
      original_title: 'Spider-Man: Across the Spider-Verse',
      overview:
        'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
      poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 16, 878],
      popularity: 2267.849,
      release_date: '2023-05-31',
      video: false,
      vote_average: 8.692,
      vote_count: 1517,
    },
    {
      adult: false,
      backdrop_path: '/rogeBJK44LtWynOqzMFmEF30T80.jpg',
      id: 812225,
      title: 'Black Clover: Sword of the Wizard King',
      original_language: 'ja',
      original_title: 'ブラッククローバー 魔法帝の剣',
      overview:
        'As a lionhearted boy who can’t wield magic strives for the title of Wizard King, four banished Wizard Kings of yore return to crush the Clover Kingdom.',
      poster_path: '/gNVYqSnZ89UyTZ977SEJLze4g3X.jpg',
      media_type: 'movie',
      genre_ids: [16, 14, 28, 12],
      popularity: 411.639,
      release_date: '2023-06-16',
      video: false,
      vote_average: 8.876,
      vote_count: 85,
    },
    {
      adult: false,
      backdrop_path: '/c6Splshb8lb2Q9OvUfhpqXl7uP0.jpg',
      id: 717930,
      title: 'Kandahar',
      original_language: 'en',
      original_title: 'Kandahar',
      overview:
        'After his mission is exposed, an undercover CIA operative stuck deep in hostile territory in Afghanistan must fight his way out, alongside his Afghan translator, to an extraction point in Kandahar, all whilst avoiding elite enemy forces and foreign spies tasked with hunting them down.',
      poster_path: '/lCanGgsqF4xD2WA5NF8PWeT3IXd.jpg',
      media_type: 'movie',
      genre_ids: [28, 53],
      popularity: 327.244,
      release_date: '2023-05-25',
      video: false,
      vote_average: 5.108,
      vote_count: 65,
    },
    {
      adult: false,
      backdrop_path: '/1R6cvRtZgsYCkh8UFuWFN33xBP4.jpg',
      id: 545609,
      title: 'Extraction',
      original_language: 'en',
      original_title: 'Extraction',
      overview:
        'Tyler Rake, a fearless mercenary who offers his services on the black market, embarks on a dangerous mission when he is hired to rescue the kidnapped son of a Mumbai crime lord.',
      poster_path: '/nygOUcBKPHFTbxsYRFZVePqgPK6.jpg',
      media_type: 'movie',
      genre_ids: [28, 53],
      popularity: 656.387,
      release_date: '2020-04-24',
      video: false,
      vote_average: 7.347,
      vote_count: 5118,
    },
    {
      adult: false,
      backdrop_path: '/1inZm0xxXrpRfN0LxwE2TXzyLN6.jpg',
      id: 603692,
      title: 'John Wick: Chapter 4',
      original_language: 'en',
      original_title: 'John Wick: Chapter 4',
      overview:
        'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
      poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
      media_type: 'movie',
      genre_ids: [28, 53, 80],
      popularity: 3273.465,
      release_date: '2023-03-22',
      video: false,
      vote_average: 7.911,
      vote_count: 3124,
    },
    {
      adult: false,
      backdrop_path: '/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
      id: 502356,
      title: 'The Super Mario Bros. Movie',
      original_language: 'en',
      original_title: 'The Super Mario Bros. Movie',
      overview:
        'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
      poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
      media_type: 'movie',
      genre_ids: [16, 10751, 12, 14, 35],
      popularity: 2731.516,
      release_date: '2023-04-05',
      video: false,
      vote_average: 7.807,
      vote_count: 4895,
    },
    {
      adult: false,
      backdrop_path: '/cSYLX73WskxCgvpN3MtRkYUSj1T.jpg',
      id: 976573,
      title: 'Elemental',
      original_language: 'en',
      original_title: 'Elemental',
      overview:
        'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
      poster_path: '/8riWcADI1ekEiBguVB9vkilhiQm.jpg',
      media_type: 'movie',
      genre_ids: [16, 35, 10751, 14, 10749],
      popularity: 543.291,
      release_date: '2023-06-14',
      video: false,
      vote_average: 7.5,
      vote_count: 53,
    },
    {
      adult: false,
      backdrop_path: '/vV5LKWmuysEe5wsuZJGbdiL5XJ2.jpg',
      id: 194583,
      name: 'The Walking Dead: Dead City',
      original_language: 'en',
      original_name: 'The Walking Dead: Dead City',
      overview:
        'Maggie and Negan travel to post-apocalyptic Manhattan - long ago cut off from the mainland. The crumbling city is filled with the dead and denizens who have made it a world full of anarchy, danger, beauty, and terror.',
      poster_path: '/wq3vuQzQgbS83zX3malAFWMsSwX.jpg',
      media_type: 'tv',
      genre_ids: [18, 10759, 10765],
      popularity: 653.688,
      first_air_date: '2023-06-18',
      vote_average: 8.552,
      vote_count: 58,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/bw2tNvU2ajjPPoqdEAZAXLBCQG.jpg',
      id: 539972,
      title: 'Kraven the Hunter',
      original_language: 'en',
      original_title: 'Kraven the Hunter',
      overview:
        'Sergei Kravinoff is a big game hunter, who takes a magical serum giving him superhuman abilities and a longer life.',
      poster_path: '/1GvBhRxY6MELDfxFrete6BNhBB5.jpg',
      media_type: 'movie',
      genre_ids: [28, 878],
      popularity: 19.975,
      release_date: '2023-10-04',
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/8rpDcsfLJypbO6vREc0547VKqEv.jpg',
      id: 76600,
      title: 'Avatar: The Way of Water',
      original_language: 'en',
      original_title: 'Avatar: The Way of Water',
      overview:
        'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
      poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
      media_type: 'movie',
      genre_ids: [878, 12, 28],
      popularity: 1164.971,
      release_date: '2022-12-14',
      video: false,
      vote_average: 7.7,
      vote_count: 8663,
    },
    {
      adult: false,
      backdrop_path: '/3HSGXeu2v171vGyJEW8FmQRHjLJ.jpg',
      id: 986070,
      title: 'The Wrath of Becky',
      original_language: 'en',
      original_title: 'The Wrath of Becky',
      overview:
        'Two years after she escaped a violent attack on her family, 16-year-old Becky attempts to rebuild her life in the care of an older woman -- a kindred spirit named Elena. However, when a violent group known as the Noble Men break into their home, attack them and take their beloved dog, Becky must return to her old ways to protect herself and her loved ones.',
      poster_path: '/3LShl6EwqptKIVq6NWOZ0FbZHEe.jpg',
      media_type: 'movie',
      genre_ids: [28, 27, 53],
      popularity: 59.388,
      release_date: '2023-05-26',
      video: false,
      vote_average: 6.471,
      vote_count: 17,
    },
    {
      adult: false,
      backdrop_path: '/35OoC3JxHXrAOg4FAa2DrPCzUX9.jpg',
      id: 1010581,
      title: 'My Fault',
      original_language: 'es',
      original_title: 'Culpa mía',
      overview:
        "Noah must leave her city, boyfriend, and friends to move into William Leister's mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.",
      poster_path: '/w46Vw536HwNnEzOa7J24YH9DPRS.jpg',
      media_type: 'movie',
      genre_ids: [10749, 18],
      popularity: 1146.667,
      release_date: '2023-06-08',
      video: false,
      vote_average: 8.371,
      vote_count: 654,
    },
    {
      adult: false,
      backdrop_path: '/tBimLn6VICHRjvCWPRWxp9X0F7Q.jpg',
      id: 812635,
      title: 'Chevalier',
      original_language: 'en',
      original_title: 'Chevalier',
      overview:
        'The illegitimate son of an African slave and a French plantation owner, Bologne rises to improbable heights in French society as a celebrated violinist-composer and fencer, complete with an ill-fated love affair and a falling out with Marie Antoinette and her court. Inspired by the incredible true story of composer Joseph Bologne, Chevalier de Saint-Georges.',
      poster_path: '/p5f9WgN9ZQ0rEdc2ywfLp8uJTt8.jpg',
      media_type: 'movie',
      genre_ids: [10402, 18, 36],
      popularity: 67.488,
      release_date: '2023-04-20',
      video: false,
      vote_average: 6.3,
      vote_count: 20,
    },
    {
      adult: false,
      backdrop_path: '/qWQSnedj0LCUjWNp9fLcMtfgadp.jpg',
      id: 667538,
      title: 'Transformers: Rise of the Beasts',
      original_language: 'en',
      original_title: 'Transformers: Rise of the Beasts',
      overview:
        'When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.',
      poster_path: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 1946.7,
      release_date: '2023-06-06',
      video: false,
      vote_average: 7.2,
      vote_count: 355,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};

export default MOVIES